//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminler
    {
        public int AdminID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Kullanıcı_Tipi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
        public string Email { get; set; }
        public string TelefonNo { get; set; }
        public string İl { get; set; }
        public string İlce { get; set; }
        public string Adres { get; set; }
    
        public virtual Cinsiyetler Cinsiyetler { get; set; }
    }
}
