//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arabalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arabalar()
        {
            this.Kiralamalar = new HashSet<Kiralamalar>();
        }
    
        public int ArabaID { get; set; }
        public Nullable<int> ArabaMarkaID { get; set; }
        public Nullable<int> ArabaModelID { get; set; }
        public Nullable<int> ArabaVitesTurID { get; set; }
        public Nullable<int> ArabaTurID { get; set; }
        public Nullable<int> ArabaResimID { get; set; }
        public string Plaka { get; set; }
        public string YakitTuru { get; set; }
        public string Fiyat { get; set; }
        public string Yıl { get; set; }
        public int KoltukSayisi { get; set; }
        public decimal BagajHacmi { get; set; }
        public string MotorHacmi { get; set; }
        public int MotorGucu { get; set; }
        public bool Klima { get; set; }
        public bool Navigasyon { get; set; }
        public bool GeriGorusKamerasi { get; set; }
        public bool ParkSensoru { get; set; }
        public bool Bluetooth { get; set; }
        public bool USBPortu { get; set; }
        public bool Sunroof { get; set; }
    
        public virtual ArabaMarkalari ArabaMarkalari { get; set; }
        public virtual ArabaModelleri ArabaModelleri { get; set; }
        public virtual ArabaResimleri ArabaResimleri { get; set; }
        public virtual ArabaTurleri ArabaTurleri { get; set; }
        public virtual ArabaVitesTurleri ArabaVitesTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralamalar> Kiralamalar { get; set; }
    }
}
