//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralamalar
    {
        public int KiraID { get; set; }
        public int ArabaID { get; set; }
        public int MusteriID { get; set; }
        public System.DateTime KiraTarih { get; set; }
        public string KiraDurum { get; set; }
    
        public virtual Arabalar Arabalar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
