//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralamaDBEntities : DbContext
    {
        public AracKiralamaDBEntities()
            : base("name=AracKiralamaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminler> Adminler { get; set; }
        public virtual DbSet<ArabaMarkalari> ArabaMarkalari { get; set; }
        public virtual DbSet<ArabaModelleri> ArabaModelleri { get; set; }
        public virtual DbSet<ArabaResimleri> ArabaResimleri { get; set; }
        public virtual DbSet<ArabaTurleri> ArabaTurleri { get; set; }
        public virtual DbSet<ArabaVitesTurleri> ArabaVitesTurleri { get; set; }
        public virtual DbSet<Cinsiyetler> Cinsiyetler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Arabalar> Arabalar { get; set; }
        public virtual DbSet<Kiralamalar> Kiralamalar { get; set; }
    }
}
