//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Kiralamalar = new HashSet<Kiralamalar>();
        }
    
        public int MusteriID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Kullanıcı_Tipi { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string Email { get; set; }
        public string TelefonNo { get; set; }
        public string İl { get; set; }
        public string İlce { get; set; }
        public string Adres { get; set; }
        public string EhliyetNo { get; set; }
        public System.DateTime EhliyetAlımTarihi { get; set; }
        public string AcilDurumKisiAdi { get; set; }
        public string AcilDurumKisiNO { get; set; }
        public string AcilDurumYakınlıkDerecesi { get; set; }
    
        public virtual Cinsiyetler Cinsiyetler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralamalar> Kiralamalar { get; set; }
    }
}
